Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic 
operations like: 
a) Addition of 2 in all the element  
b) Multiply 3 with all the elements 
c) Divide every element by 2 d_ ucs420_<your_name>>.d_ ucs420_<your_name>>.

In [13]:
import numpy as np

# Create a 1D NumPy array with 5 elements
arr = np.array([1, 2, 3, 4, 5])

# (a) Addition of 2 to all elements
arr_add = arr + 2
print("After addition:", arr_add)

# (b) Multiplication of all elements by 3
arr_mult = arr * 3
print("After multiplication:", arr_mult)

# (c) Division of all elements by 2
arr_div = arr / 2
print("After division:", arr_div)


After addition: [3 4 5 6 7]
After multiplication: [ 3  6  9 12 15]
After division: [0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array: 
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
b) Find the most frequent value and their indice(s) in the following arrays: 
i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

(a) Reverse the NumPy array

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
arr_reversed = arr[::-1]
print("Reversed Array:", arr_reversed)


Reversed Array: [5 4 6 3 2 1]


(b) Find the most frequent value and its indices


In [17]:
import numpy as np

# Function to find the most frequent value and its indices
def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_freq_value = values[np.argmax(counts)]
    indices = np.where(arr == max_freq_value)
    return max_freq_value, indices[0]

# (i) For x array
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
max_val_x, indices_x = most_frequent(x)
print(f"Most frequent value in x: {max_val_x}, Indices: {indices_x}")

# (ii) For y array
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
max_val_y, indices_y = most_frequent(y)
print(f"Most frequent value in y: {max_val_y}, Indices: {indices_y}")


Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access 
elements using row and column indices as follows: 
a) Access 1st row, 2nd column  
b) Access 3rd row, 1st column 

In [19]:
import numpy as np

arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

# (a) Access 1st row, 2nd column
print("Element at 1st row, 2nd column:", arr[0, 1])

# (b) Access 3rd row, 1st column
print("Element at 3rd row, 1st column:", arr[2, 0])


Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly 
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, 
shape, total elements, the data type of each element and total number of bytes consumed 
by the array. Find the transpose of this array using reshape() attribute. Can we do the same 
with T attribute? 

In [21]:
import numpy as np

# Create a 1D NumPy array using linspace
aptik_pandey = np.linspace(10, 100, 25)

# Print required details
print("Array:", aptik_pandey)
print("Dimensions:", aptik_pandey.ndim)
print("Shape:", aptik_pandey.shape)
print("Total elements:", aptik_pandey.size)
print("Data type:", aptik_pandey.dtype)
print("Total bytes consumed:", aptik_pandey.nbytes)

# Find the transpose using reshape
transposed_array = aptik_pandey.reshape(25, 1)
print("Transposed Array using reshape:\n", transposed_array)

# Check if T attribute can do the same
print("Using T attribute does not work for 1D array:", aptik_pandey.T)


Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200
Transposed Array using reshape:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute does not work for 1D array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> 
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, 
median, max, min, unique elements. Reshape the array to four rows and three columns and 
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three 
columns and name it as resized_ ucs420_<your_namment

In [23]:
import numpy as np

# Create a 2D NumPy array
ucs420_aptik = np.array([[10, 20, 30, 40], 
                         [50, 60, 70, 80], 
                         [90, 15, 20, 35]])

# Compute statistics
print("Mean:", np.mean(ucs420_aptik))
print("Median:", np.median(ucs420_aptik))
print("Max value:", np.max(ucs420_aptik))
print("Min value:", np.min(ucs420_aptik))
print("Unique elements:", np.unique(ucs420_aptik))

# Reshape the array to 4 rows and 3 columns
reshaped_ucs420_aptik = ucs420_aptik.reshape(4, 3)
print("Reshaped Array (4x3):\n", reshaped_ucs420_aptik)

# Resize the array to 2 rows and 3 columns
resized_ucs420_aptik = np.resize(ucs420_aptik, (2, 3))
print("Resized Array (2x3):\n", resized_ucs420_aptik)


Mean: 43.333333333333336
Median: 37.5
Max value: 90
Min value: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
